### ISSUE TITLE
Without text

### ISSUE THREAD

**Issue by gutisalex** [CreativeBulma/bulma-divider#2]
Missing the option to use this without having a text. The old version before was able to do that. Now I am having a gap there!

### Code example: 
`<div class="divider" />`

### Screenshot:
![image](https://user-images.githubusercontent.com/52527652/82635161-e9d15f80-9bff-11ea-871f-791195da3c11.png)

**Comment by kevzzsk** [comment]
Not sure why that's not the default case but in the meantime you can customize on your own (https://demo.creativebulma.net/components/divider/1.1/how-to/customize/)
 
Im using saas, so you can add 

```
$divider-margin-inner-size: 0px;

@import '@creativebulma/bulma-divider'
```

to your saas import and it should remove the blank middle page.

**Comment by Didstriker** [comment]
I had the same issue, but I managed to get the desired functionality using CSS's :empty

`:empty.divider:before {
    margin-right: 0;
}
:empty.divider:after {
    margin-left: 0;
}`

**Comment by MetallianFR68** [comment]
This should be integrated by default

**Comment by lublak** [comment]
why don't you just use hr then?

```html
<hr>
```

**Comment by MicahBrown** [comment]
@lublak For the vertical divider
